   ######################
# book (meta) info

title: Retour d'expérience
author: 
  name: Mourad Chaibi  (CGI))

github:
  url: "https://dromadev.github.io"


########
# more settings

collections:
  chapters:
      output: false

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md

   