baseURL = "https://www.cocoon-arolla.com/"
# baseURL = "https://arolla-cocoon.netlify.com/"

languageCode = "fr"
title = "Cocoon & Cosy tentes de luxe/luxury tents in Arolla"
theme = "airspace"

# Pas de Taxonomies
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "UA-121816579-1"

enableGitInfo = true
pygmentsCodeFences = true

[menu]

  [[menu.header]]
    weight = 1
    name = "Home"
    url = "/"
  [[menu.header]]
    weight = 2
    name = "www.camping-arolla.com"
    url = "https://www.camping-arolla.com"
  [[menu.header]]
    weight = 3
    name = "Prestations/services"
    url = "/service/"
  [[menu.header]]
    weight = 4
    name = "Online reservation"
    url = "#reserve"
  [[menu.header]]
    weight = 5
    name = "Contact & directions"
    url = "/contact/"
  [[menu.header]]
    weight = 7
    name = "Webcam & meteo"
    url = "/webcam/"

  [[menu.footer]]
    weight = 1
    name = "Home"
    url = "/"
  [[menu.footer]]
    weight = 2
    name = "www.camping-arolla.com"
    url = "https://www.camping-arolla.com"
  [[menu.footer]]
    weight = 3
    name = "Prestations/services"
    url = "/service/"
  [[menu.footer]]
    weight = 4
    name = "Online reservation"
    url = "#reserve"
  [[menu.footer]]
    weight = 5
    name = "Contact & directions"
    url = "/contact/"
  [[menu.footer]]
    weight = 7
    name = "Webcam & meteo"
    url = "/webcam/"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "6 January 2006"
  home = "Home"

  logo = "/images/logo-blanc.png"
  logo_size = "90"

  # pour SEO/opengraph
  images = ["img/slider-bg.jpg", "img/wrapper-img.png"]
  videos = ["https://vimeo.com/277877979"]

  description = "Tentes de luxe, lit 2 personnes & Poêle à bois. Vous avez toujours rêvé de venir camper, mais vous n’êtes pas un aventurier aguerri? Venez passer une nuit inoubliable en plein coeur des montagnes, perchés à 1950m d'altitude, le tout dans une ambiance confortable & chaleureuse!"

  legaltext = "Mentions légales"
  cookielegalurl = "legal"

  [params.msgboxlocal]
    enable = true
    title = "Retrouvez nous / find us"
    text = "à L'hôtel de La Gouille"
    url = "https://www.pension-du-lac-bleu.ch/blog/une-nouvelle-equipe/"

  [params.open]
    open = false
    textopen  = "Le camping est ouvert du 1 juin au 15 septembre 2019."
    textclose = "Fermeture annuelle - réouverture en Juin 2019."

  [params.slider]
    enable = true
    title = "COCOONING & COSY"
    subtitle = "Tentes de luxe, lit 2 personnes & poêle à bois.<br>Vous avez toujours rêvé de venir camper, mais vous n’êtes pas un aventurier aguerri? <br> Venez passer une nuit inoubliable en plein coeur des montagnes, perchés à 1950m d'altitude, le tout dans une ambiance confortable & chaleureuse!<p>Luxury Tents, 2 Person Bed & Wood Burning Stove. <br> Have you always dreamed of camping, but you are not a seasoned adventurer? <br> Come and spend an unforgettable night in the heart of the mountains, perched at 1950m altitude, all in a comfortable and warm atmosphere!"

  [params.wrapper]
    enable = true
    title = "A propos de nous / About Us ... Camping Arolla"
    italic = "Amoureux de la nature, venez découvrir le camping le plus haut d'Europe, perché à 1.950m d'altitude dans un environnement totalement naturel au pied des sommets et glaciers."
    paragraph = "In the heart of the Swiss Alps, at an altitude of 1 950 meters, Camping Arolla is situated in a beautiful position with a panorama of stunning mountains and glaciers. It offers dozens of routes and walks of every variety starting just a stone’s throw away."
    masterwebsite = "https://www.camping-arolla.com"

  [params.feature]
    enable = true
    title = "Tentes de luxe / Luxury tents COCOONING & COSY"
    content = ""
    [params.feature.button]
      caption = "Book online"
      url = "#reserve"


  [params.call]
    enable = true
    title = "Appelez / Call: +41(0)27 283 22 95"
    paragraph = "De Juin à Septembre / From June to September"

  [params.reserve]
    enable = true
    cid = 151
    title = "Online reservation"
    paragraph = "2 tentes disponibles/2 tents available"
    checkin ="Check-in : 16-19h / Check-out : 11-12h"
    warning_spam_title ="After your reservation / après votre réservation ... check your spam folder / vérifiez votre dossier de spam"
    warning_spam_en = "WE DO SEND confirmation mails. So please, please, check your spam filter & junk mail folder if you do not see those mails"
    warning_spam_fr = "NOUS ENVOYONS des mails de confirmation. Alors, s'il vous plaît, vérifiez votre filtre de courrier indésirable et votre dossier de spam si vous ne voyez pas ces messages"

  # gestion du mode de contact
  [params.zotabox]
    enable = false
    title  = "Utilisez le bouton de contact à droite"
    text   = "Nous nous ferons un plaisir de vous répondre dans les meilleurs délais"
    url    = "1/2/1212f7bbd05c5aaf387f9cfcd348585e"
  [params.contact]
    title = "Contactez nous / Drop us a note"
    subtitle = "Utilisez le formulaire pour nous laisser un message."
    [params.contact.form]
      enable = true
      name = "Votre nom / Your name"
      email = "Votre email / Your email"
      subject = "Votre sujet / Your subject"
      message = "Votre message / Your message"
      button = "Envoyer le message / Send message"
    [params.contact.box]
      title = "Camping Arolla SARL"
      address = "Route de Tsalion - 1986 Arolla - Switzerland"
      email = "Utilisez le formulaire de contact à droite / Use contact form on the right."
      phone = "Téléphone / Phone: +41 (0)27 283 22 95"
    [params.contact.gmaps]
      title = "Nous trouver avec OpenStreet Maps / Find us with OpenStreet Maps"

  [params.meteo]
    enable = true
    title = "Prévisions météo / Weather forecast"
    subtitle_fr = "Arolla ayant un micro-climat plus ensoleillé, les prévisions sont souvent fausses ... reportez vous aux images en direct"
    subtitle_en = "Arolla has a sunnier micro-climate, the forecasts are often false ... refer to real and live images."
    paragraph_en = "Meteoblue is the most accurate site for Arolla. It is a meteorological service created at the University of Basel, Switzerland, in cooperation with the U.S. National Oceanic and Atmospheric Administration and the National Centers for Environmental Prediction. This is the favoured information source for alpinists, para-gliders, astronomers and farmers."
    paragraph_fr = "Meteoblue est le site le plus fiable pour Arolla. C'est un service météorologique créé à l'Université de Bâle, en Suisse, en coopération avec la NOAA des États-Unis et les Centres nationaux de prévision environnementale. C'est la source d'information privilégiée pour les alpinistes, les parapentistes, les astronomes et les agriculteurs."

  [params.webcam]
    # image directe depuis mangocam
    titleimagefixe = "Live images / Images en direct"
    subtitleimagefixe = "La webcam du camping"
    enableimagefixe = true
    # urlimagefixe = "https://www120.mangocam.com/c/campingarollaimage/img.php"
    urlimagefixe = "https://www124.mangocam.com/c/campingarollaimage/img.php"
    webcamwarning = "DIRECT LIVE - automatic refresh every 10 seconds"

    # iframes mangocam
    enableimage = false
    enablestream = false
    server = "https://www.mangocam.com"
    accountimage  = "c/campingarollaimage"
    accountstream = "c/campingarollastream"
    address = "idx.php" # "frame.php"
    sizeximage = 1280
    sizeyimage = 720
    sizexstream = 640
    sizeystream = 480
    subtitleimagestream = "1 image / 10 sec"

    # timelapse from https://www.lookr.com/
    enabletimelapse = true
    timelapseembeded = false
    titletimelapse = "Vidéo accélérée / timelapse de la webcam"
    subtitletimelapse ="Choose from last 24h or 30 days at camping Arolla"
    copyrighttimelapse = "Time lapse Web player provided courtesy of www.lookr.com"
    idtimelapse = "1534093781"

# RGPD compliant
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.speakerDeck]
    disable = true
  [privacy.twitter]
    disable = true
    enableDNT = true
  [privacy.vimeo]
    disable = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

# Pour générer le _redirects pour Netlify
[outputs]
home = [ "HTML", "RSS", "REDIR" ]

[mediaTypes]
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

[outputFormats]
[outputFormats.REDIR]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true
